HouseHoldFront/Models/HouseHoldInvites.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HouseHoldFront.Models
{
    public class HouseHoldInvites
    {
        public int Id { get; set; }

        public int HouseHoldId { get; set; }
        public virtual HouseHolds HouseHold { get; set; }

        public string InvitedUserId { get; set; }
        public virtual ApplicationUser InvitedUser { get; set; }
    }
}

HouseHoldFront/Models/HouseHolds.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HouseHoldFront.Models
{
    public class HouseHolds
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string CreatorId { get; set; }
        public virtual ApplicationUser Creator { get; set; }

        public virtual ICollection<ApplicationUser> UsersInHouseHold { get; set; }
        
    }
}

HouseHoldFront/Controllers/HouseHoldsController.cs
using HouseHoldFront.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace HouseHoldFront.Controllers
{
    public class HouseHoldsController : Controller
    {
        // GET: HouseHolds
        public ActionResult Index()
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.GetAsync("http://localhost:58110/api/households/View").Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<List<ViewHouseHoldViewModel>>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        public ActionResult Create(CreateHouseHoldViewModel model)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var parameters = new List<KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Name", model.Name));
            var formEncodedValues = new FormUrlEncodedContent(parameters);
            var result =
               httpClient.PostAsync("http://localhost:58110/api/households/PostHouseHolds", formEncodedValues).Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHold = JsonConvert
                   .DeserializeObject<HouseHolds>(jsonString);
                return View(houseHold);
            }
            return View();
        }
        //public ActionResult Edit(int id)
        //{
        //    var cookie = Request.Cookies["token"];
        //    var accessToken = cookie.Value;
        //    var httpClient = new HttpClient();
        //    httpClient.DefaultRequestHeaders.Authorization =
        //       new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
        //    var result =
        //       httpClient.GetAsync("http://localhost:58110/api/households/PutHouseHolds?id" + id).Result;
        //    var jsonString = result.Content.ReadAsStringAsync().Result;
        //    var houseHold = JsonConvert
        //       .DeserializeObject<EditHouseHoldViewModel>(jsonString);
        //    return View(houseHold);
        //}

        public ActionResult Edit(EditHouseHoldViewModel model)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var parameters = new List<KeyValuePair<string, string>>();
            parameters.Add(new KeyValuePair<string, string>("Name", model.Name));
            var formEncodedValues = new FormUrlEncodedContent(parameters);
            var result =
               httpClient.PostAsync("http://localhost:58110/api/households/PutHouseHolds?id", formEncodedValues).Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHold = JsonConvert
                   .DeserializeObject<EditHouseHoldViewModel>(jsonString);
                return View(houseHold);
            }
            return View();
        }

        public ActionResult ViewMembers()
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.GetAsync("http://localhost:58110/api/households/ViewMembers").Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHolds = JsonConvert
                   .DeserializeObject<List<HouseHoldMembersViewModel>>(jsonString);
                return View(houseHolds);
            }
            return View();
        }

        //public ActionResult InviteMembers(int id)
        //{
        //    var cookie = Request.Cookies["token"];
        //    if (cookie == null)
        //    {
        //        return RedirectToAction("Login", "Account");
        //    }
        //    var accessToken = cookie.Value;
        //    var httpClient = new HttpClient();
        //    httpClient.DefaultRequestHeaders.Authorization =
        //       new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
        //    var result =
        //       httpClient.PostAsync("http://localhost:58110/api/households/HouseHoldInvites?id=" +id , null).Result;
        //    if (result.StatusCode == System.Net.HttpStatusCode.OK)
        //    {
        //        var jsonString = result.Content.ReadAsStringAsync().Result;
        //        var houseHolds = JsonConvert
        //           .DeserializeObject<HouseHolds>(jsonString);
        //        return View(houseHolds);
        //    }
        //    return View();
        //}

        public ActionResult Leave(int Id)
        {
            var cookie = Request.Cookies["token"];
            if (cookie == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var accessToken = cookie.Value;
            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization =
               new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
            var result =
               httpClient.PostAsync("http://localhost:58110/api/HouseHolds/Leave?Id=" + Id, null).Result;
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var houseHold = JsonConvert
                   .DeserializeObject<HouseHolds>(jsonString);
                return View(houseHold);
            }
            return View();
        }

        //public ActionResult HouseHoldJoin(int Id)
        //{
        //    var cookie = Request.Cookies["token"];
        //    if (cookie == null)
        //    {
        //        return RedirectToAction("Login", "Account");
        //    }
        //    var accessToken = cookie.Value;
        //    var httpClient = new HttpClient();
        //    httpClient.DefaultRequestHeaders.Authorization =
        //       new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);

        //    var result =
        //       httpClient.PostAsync("http://localhost:58110/api/households/HouseHoldJoin?InvitedUserId", formEncodedValues).Result;
        //    if (result.StatusCode == System.Net.HttpStatusCode.OK)
        //    {
        //        var jsonString = result.Content.ReadAsStringAsync().Result;
        //        var houseHold = JsonConvert
        //           .DeserializeObject<HouseHolds>(jsonString);
        //        return View(houseHold);
        //    }
        //   return View();
        // }
    }
}

HouseHoldFront/Views/HouseHolds/Create.cshtml
@model  HouseHoldFront.Models.HouseHolds
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "HouseHolds", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Create</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.CreatorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
  
</div>
}

HouseHoldFront/Views/HouseHolds/Delete.cshtml
@model  HouseHoldFront.Models.LeaveHouseHoldBindingModel
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<div class="row">
    <div class="col-lg-12">

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Bug</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UsersInHouseHold)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UsersInHouseHold)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

HouseHoldFront/Views/HouseHolds/Edit.cshtml
@model  HouseHoldFront.Models.EditHouseHoldViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "HouseHolds", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.CreatorId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatorId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

HouseHoldFront/Views/HouseHolds/HouseHoldInvites.cshtml
@{
    ViewBag.Title = "HouseHoldInvites";
}

<h2>HouseHoldInvites</h2>

HouseHoldFront/Views/HouseHolds/HouseHoldJoin.cshtml
@{
    ViewBag.Title = "HouseHoldJoin";
}

<h2>HouseHoldJoin</h2>

HouseHoldFront/Views/HouseHolds/Index.cshtml
@model List<HouseHoldFront.Models.ViewHouseHoldViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>HouseHolds</h2>

<div>
    @Html.ActionLink("CreateHouseHolds", "Create")
</div>

<p>HouseHolds List</p>

@if (Model == null)
{
    <p>Nothing Created By You</p>
}
else
{
    <table>
        <thead>
            <tr>
                Name
            </tr>
            <tr>
                Number of Members
            </tr>
        </thead>
        <tbody>
            @foreach (var household in Model)
            {
                <tr>
                    <td>
                        @household.Name
                    </td>

                    <td>
                        @household.NumberOfUsers
                    </td>
                    
                    <td>
                        @Html.ActionLink("Edit", "Edit") |
                        @Html.ActionLink("Members", "ViewMembers") |
                        @Html.ActionLink("invite", "InviteMembers") |
                        @Html.ActionLink("Delete", "Leave", new { id = household.Id}) 
                    </td>
                </tr>
            }
        </tbody>
    </table>

     <div>
        @Html.ActionLink("Join Members in HouseHolds ", "HouseHoldJoin")
    </div>

}

HouseHoldFront/Views/HouseHolds/ViewMembers.cshtml
@model List<HouseHoldFront.Models.HouseHoldMembersViewModel>

@{
    ViewBag.Title = "ViewMembers";
}

<h2>ViewMembers</h2>

<p>HouseHolds  Members List</p>

@if (Model == null)
{
    <p>Nothing Created By You</p>
}
else
{
    <table>
        <thead>
            <tr>
                Name
            </tr>
            <tr>
                Email
            </tr>
        </thead>
        <tbody>
            @foreach (var household in Model)
            {
                <tr>
                    <td>
                        @household.Name
                    </td>
                    <td>
                        @household.Email
                    </td>
                </tr>
            }
        </tbody>
    </table>


}